# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "ubuntu/focal64"
  
  # Configuration de la machine unique pour la partie 2
  config.vm.define "chillionS" do |server|
    server.vm.hostname = "chillionS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--name", "chillionS"]
    end

    # Copie des fichiers de configuration
    server.vm.provision "file", source: "confs/", destination: "/tmp/confs"
    
    # Installation et configuration
    server.vm.provision "shell", path: "scripts/install_k3s.sh"
    server.vm.provision "shell", path: "scripts/setup_apps.sh"
  end
end
